<?php 
/**
 * ZF2 Buch Kapitel 21
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */

$this->headTitle('Listings - Kapitel 21');
$this->pageTitle('Listings - Kapitel 21');
?>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing2101">Listing 21.1</a></td>
<td>Modulkonfiguration für <code>Cms</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing2102">Listing 21.2</a></td>
<td><code>CmsService</code> zum Lesen und Schreiben von Textblöcken</td>
</tr>
<tr>
<td><a href="/listing/listing2103">Listing 21.3</a></td>
<td>Textblock <code>application_index_index.html</code> für Angebot auf Startseite</td>
</tr>
<tr>
<td><a href="/listing/listing2104">Listing 21.4</a></td>
<td><code>CmsContentBlock</code> View-Helper gibt Textblock aus</td>
</tr>
<tr>
<td><a href="/listing/listing2105">Listing 21.5</a></td>
<td><code>ContentBlockForm</code> für die Bearbeitung der Textblöcke</td>
</tr>
<tr>
<td><a href="/listing/listing2106">Listing 21.6</a></td>
<td>Erweiterter <code>CmsService</code></td>
</tr>
<tr>
<td><a href="/listing/listing2107">Listing 21.7</a></td>
<td>Erweiterter <code>CmsContentBlock</code> zum Bearbeiten von Textblöcken</td>
</tr>
<tr>
<td><a href="/listing/listing2108">Listing 21.8</a></td>
<td>JavaScript Funktionen in <code>/public/js/cms.js</code></td>
</tr>
<tr>
<td><a href="/listing/listing2109">Listing 21.9</a></td>
<td><code>CmsController</code> zum Speichern der Textblöcke</td>
</tr>
</tbody>
</table>
