<?php 
/**
 * ZF2 Buch Kapitel 21
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 21.3 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 21.3');
$this->pageTitle('Listing 21.3');
?>
<h3>Textblock <code>application_index_index.html</code> für Angebot auf Startseite</h3>
<pre>
&lt;h3&gt;Aktuelles Angebot&lt;/h3&gt;
&lt;p&gt;Ab sofort gibt es f&amp;uuml;r jede bestellte &lt;strong&gt;Vollkornpizza&lt;/strong&gt; 
eine Flasche Milch (0.5l) &lt;strong&gt;gratis&lt;/strong&gt; dazu. Erm&amp;ouml;glicht 
wird diese Aktion von einem unserer besten Kunden, dem Milchbauern 
&lt;strong&gt;Horst&lt;/strong&gt; aus Dingenskirchen. Nur solange der Vorrat reicht!&lt;/p&gt;
&lt;p&gt;&lt;strong&gt;Grazie Horst!&lt;/strong&gt;&lt;/p&gt;
</pre>
