<?php 
/**
 * ZF2 Buch Kapitel 21
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 21.2 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 21.2');
$this->pageTitle('Listing 21.2');
?>
<h3><code>CmsService</code> zum Lesen und Schreiben von Textblöcken</h3>
<pre>
&lt;?php 
namespace Cms\Service;

class CmsService implements CmsServiceInterface
{
    public function loadBlock($block)
    {
        $fileName = LUIGI_ROOT . '/data/cms/' . $block . '.html';

        if (!file_exists($fileName)) {
            return '';
        }

        $content = implode('', file($fileName));

        return $content;
    }
}
</pre>
