<?php 
/**
 * ZF2 Buch Kapitel 21
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 21.4 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 21.4');
$this->pageTitle('Listing 21.4');
?>
<h3><code>CmsContentBlock</code> View-Helper gibt Textblock aus</h3>
<pre>
&lt;?php
namespace Cms\View\Helper;

use Cms\Service\CmsServiceInterface;
use Zend\View\Helper\AbstractHelper;

class CmsContentBlock extends AbstractHelper
{
    protected $cmsService;

    public function __construct(CmsServiceInterface $cmsService)
    {
        $this->setCmsService($cmsService);
    }

    public function setCmsService(CmsServiceInterface $cmsService = null)
    {
        $this->cmsService = $cmsService;
        return $this;
    }
    
    public function getCmsService()
    {
        return $this->cmsService;
    }
    
    public function __invoke($block)
    {
        return $this->getCmsService()->loadBlock($block);
    }
}
</pre>
