<?php 
/**
 * ZF2 Buch Kapitel 21
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 21.8 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 21.8');
$this->pageTitle('Listing 21.8');
?>
<h3>JavaScript Funktionen in <code>/public/js/cms.js</code></h3>
<pre>
function cmsEditContentBlock(block) {
    document.getElementById(block + "_uneditable").style.display = "none";
    document.getElementById(block).style.display = "block";
    document.getElementById("cms_edit_" + block).disabled = "disabled";
    document.getElementById("cms_save_" + block).disabled = false;
    document.getElementById("cms_cancel_" + block).disabled = false;
    document.getElementById(block).focus();
}

function cmsCancelContentBlock(block) {
    document.getElementById(block + "_uneditable").style.display = "block";
    document.getElementById(block).style.display = "none";
    document.getElementById("cms_edit_" + block).disabled = false;
    document.getElementById("cms_save_" + block).disabled = "disabled";
    document.getElementById("cms_cancel_" + block).disabled = "disabled";
}

function cmsSaveContentBlock(block) {
    var form = document.getElementById("block_" + block);
    form.content.value = CKEDITOR.instances[block].getData();
    form.submit();
}
</pre>
