<?php 
/**
 * ZF2 Buch Kapitel 21
 * 
 * Das Buch 'Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung'
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 21.6 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 21.6');
$this->pageTitle('Listing 21.6');
?>
<h3>Erweiterter <code>CmsService</code></h3>
<pre>
&lt;?php
namespace Cms\Service;

use Cms\Form\ContentBlockForm;
use Cms\Form\ContentBlockFormInterface;

class CmsService implements CmsServiceInterface
{
    public function loadBlock($block)
    {
        $fileName = LUIGI_ROOT . '/data/cms/' . $block . '.html';
        
        if (!file_exists($fileName)) {
            return '';
        }
        
        $content = implode('', file($fileName));
        
        return $content;
    }
    
    public function getFormData($data)
    {
        $form = new ContentBlockForm();
        $form->addHiddenElement('url');
        $form->addHiddenElement('block');
        $form->addHiddenElement('content');
        $form->setData($data);
        $form->isValid();
        
        return $form->getData();
    }
    
    public function getForm($block, $url)
    {
        $form = new ContentBlockForm('block_' . $block);
        $form->addHiddenElement('url', $url);
        $form->addHiddenElement('block', $block);
        $form->addHiddenElement('content');
        $form->addButtonElement(
            'cms_edit_' . $block, 'Bearbeiten', 
            'cmsEditContentBlock(\'' . $block . '\');', false
        );
        $form->addButtonElement(
            'cms_save_' . $block, 'Speichern',
            'cmsSaveContentBlock(\'' . $block . '\');'
        );
        $form->addButtonElement(
            'cms_cancel_' . $block, 'Abbrechen',
            'cmsCancelContentBlock(\'' . $block . '\');'
        );
        $form->prepare();
        
        return $form;
    }
    
    public function saveBlock($block, $content)
    {
        $fileName = LUIGI_ROOT . '/data/cms/' . $block . '.html';
    
        file_put_contents($fileName, $content);
        
        return true;
    }
}
</pre>
